spec:
  destination:
    server: https://kubernetes.default.svc
  targetRevision: https://github.com/jaebchoi/test-hiveconfig5
  repo: test.org/test.git
  helm:
    valueFiles:
      - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated: {}

global:
  imagePullPolicy: Always
  dockerRepo: ghcr.io/